



###
GET   http://localhost:4000/api/cats/all

###
GET   http://localhost:4000/api/cats/65b0e1c3dfa63c7a7806ae07
###
POST http://localhost:4000/api/cats
Content-Type: application/json


    {
      "name": "Whiskers",
      "sex": "female",
      "age": "2",
      "location": "London",
      "picture": "cat2.jpg",
      "breed": "Bengal",
      "dollars": "3"
    }

###
PATCH http://localhost:4000/api/cats/65b0e264dfa63c7a7806ae0b
Content-Type: application/json

{
   "name": "changed",
        "sex": "changed",
        "age": "0",
        "location": "sad",
        "picture": "a12",
        "breed":"asda2",
        "dollars": "13322"
}

###
DELETE  http://localhost:4000/api/cats/65b0e264dfa63c7a7806ae0b